{% set name = "dotnet-core-sdk" %}
{% set version = "3.1.100" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://dot.net/v1/dotnet-install.sh  # [not win]
    sha256: cca1af4d740b9c3bb9db666f34e2870f6ae4c422922657525ce1166d0800bbca  # [not win]

build:
  skip: true  # [win]
  skip: true  # [osx]
  number: 0
  missing_dso_whitelist:
  - "*/libgssapi_krb5.so.2"
  - "*/libc.so"
  - "*/liblttng-ust.so.0"
  - "*/libz.so.1"
  - "*/libcurl.so.4"
  - "*/libstdc++.so.6"
  - "*/libcrypto.so.10"
  - "*/libnethost.so"
  - "*/libssl.so.10"

requirements:
  build:
  - {{ compiler('c') }}
  run:
  - icu  # [linux]

test:
  commands:
  - dotnet --version

about:
  home: https://github.com/dotnet/core-sdk
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '.NET Core is a cross-platform version of .NET for building websites, services, and console apps.'

  description: |
    .NET Core is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems.
  doc_url: http://docs.microsoft.com/dotnet
  dev_url: https://github.com/dotnet/core-sdk

extra:
  recipe-maintainers:
    - ZimmerA
